"""
Especificaciones de turbinas eólicas Flower Turbines.

DataFrame unificado con todos los modelos disponibles (11 turbinas).
Incluye: pequeñas VAWT, torres modulares AL13, y sistemas Eco-Roof.

Campos documentados:
- Potencia: rango 100W a 10kW
- Altura: 1.4m a 9.5m
- Producción a 12 m/s: datos reales de laboratorio
- Vida de diseño: 20-40 años
- Todos los valores en unidades SI
"""
import pandas as pd

FLOWERTURBINES_SPECS = [
    {
        "Modelo": "Small Tulip Turbine (1m)",
        "Numero_Parte": "FT 1.15M Turbine",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT (Eje Vertical, 2 Palas)",
        "Potencia_Nominal_W": 100,
        "Viento_Potencia_Nominal_ms": 14.5,
        "Produccion_12ms_Aislada_W": 62.2,
        "Produccion_12ms_Cluster5_Total_W": 723.5,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico automático integrado",
        "Tipo_Generador": "PMSG Imanes Permanentes (máx. 200W picos cortos)",
        "Polos_Generador": 8,
        "Voltaje_Salida": "110V/220V (1 Fase) / 12V/24V/48V",
        "Altura_Total_m": 1.40,
        "Altura_Pala_m": 1.149,
        "Diametro_Rotor_m": 0.55,
        "Peso_Total_kg": 20.0,
        "Material_Palas": "Plástico ABS reciclable / Termoplástico",
        "Material_Chasis": "Acero con pintura en polvo",
        "Vida_Diseno_Anos": 40,
        "Cimentacion_Requerida": "Dado concreto 0.5x0.5x0.5m o lastre Eco-Roof"
    },
    {
        "Modelo": "Survival Unit",
        "Numero_Parte": "FT 1.15M Survival Kit",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT Portátil sobre contenedor móvil",
        "Potencia_Nominal_W": 100,
        "Viento_Potencia_Nominal_ms": 14.5,
        "Produccion_12ms_Aislada_W": 62.2,
        "Produccion_12ms_Cluster5_Total_W": None,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico",
        "Tipo_Generador": "PMSG",
        "Polos_Generador": 8,
        "Voltaje_Salida": "12V (Integrada en hielera de uso rudo)",
        "Altura_Total_m": 2.08,
        "Altura_Pala_m": 1.15,
        "Diametro_Rotor_m": 0.68,
        "Peso_Total_kg": 35.0,
        "Material_Palas": "Termoplástico",
        "Material_Chasis": "Contenedor rotomoldeado móvil con ruedas",
        "Vida_Diseno_Anos": 40,
        "Cimentacion_Requerida": "Sin cimentación (autoestable)"
    },
    {
        "Modelo": "Medium Tulip Turbine (2m)",
        "Numero_Parte": "FT 2M-Lite Turbine",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT (Eje Vertical, 2 Palas)",
        "Potencia_Nominal_W": 500,
        "Viento_Potencia_Nominal_ms": 11.0,
        "Produccion_12ms_Aislada_W": 622.1,
        "Produccion_12ms_Cluster5_Total_W": 5735.0,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico programable + Freno mecánico manual",
        "Tipo_Generador": "PMSG (Electrónica 1000W en grupos de 10)",
        "Polos_Generador": 18,
        "Voltaje_Salida": "230VAC/1PH/50Hz o 240VAC/1PH/60Hz / 24V/48V",
        "Altura_Total_m": 2.62,
        "Altura_Pala_m": 2.00,
        "Diametro_Rotor_m": 1.18,
        "Peso_Total_kg": 227.25,
        "Material_Palas": "Plástico ABS / Termoplástico",
        "Material_Chasis": "Acero estructural (pedestal piramidal)",
        "Vida_Diseno_Anos": 40,
        "Cimentacion_Requerida": "Losa 2.1x2.1x0.25m o zapata 1.0x1.0x1.6m (12x M14)"
    },
    {
        "Modelo": "3-Meter Tulip Turbine",
        "Numero_Parte": "FT 3M Turbine",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT (Eje Vertical, 2 Palas)",
        "Potencia_Nominal_W": 1000,
        "Viento_Potencia_Nominal_ms": 11.0,
        "Produccion_12ms_Aislada_W": 1400.0,
        "Produccion_12ms_Cluster5_Total_W": 15000.0,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico, mecánico simple y programación automática",
        "Tipo_Generador": "PMSG (Electrónica 1500W o 2000W en grupos >=10)",
        "Polos_Generador": 18,
        "Voltaje_Salida": "230VAC/1PH/50Hz o 240VAC/1PH/60Hz / 48V",
        "Altura_Total_m": 4.07,
        "Altura_Pala_m": 3.00,
        "Diametro_Rotor_m": 1.80,
        "Peso_Total_kg": 400.0,
        "Material_Palas": "Termoplástico",
        "Material_Chasis": "Acero estructural con base de anclaje",
        "Vida_Diseno_Anos": 20,
        "Cimentacion_Requerida": "Base de concreto reforzada con pernos M14"
    },
    {
        "Modelo": "Large Tulip Turbine",
        "Numero_Parte": "FT 6M Turbine",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT (Eje Vertical, 2 Palas)",
        "Potencia_Nominal_W": 5000,
        "Viento_Potencia_Nominal_ms": 11.5,
        "Produccion_12ms_Aislada_W": 5390.0,
        "Produccion_12ms_Cluster5_Total_W": 62500.0,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico + Freno mecánico + Freno manual",
        "Tipo_Generador": "PMSG Trifásico",
        "Polos_Generador": 24,
        "Voltaje_Salida": "230VAC/3PH/60Hz o 110VAC/3PH/50Hz (Trifásico) / 48V",
        "Altura_Total_m": 6.00,
        "Altura_Pala_m": 5.00,
        "Diametro_Rotor_m": 2.45,
        "Peso_Total_kg": 1000.0,
        "Material_Palas": "Termoplástico aeroespacial",
        "Material_Chasis": "Pedestal de acero galvanizado pesado",
        "Vida_Diseno_Anos": 20,
        "Cimentacion_Requerida": "Zapata 2.5x2.5x0.9m o 2.5x4.0x0.5m"
    },
    {
        "Modelo": "AL13 Power Tower (2 Mód)",
        "Numero_Parte": "FT AL13-2M",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT Modular (Palas cruzadas a 90°)",
        "Potencia_Nominal_W": 1000,
        "Viento_Potencia_Nominal_ms": 12.0,
        "Produccion_12ms_Aislada_W": 700.0,
        "Produccion_12ms_Cluster5_Total_W": 7000.0,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 40.0,
        "Sistema_Frenado": "Electrónico + Freno mecánico",
        "Tipo_Generador": "PMSG Modular de 24V o 48V AC",
        "Polos_Generador": 18,
        "Voltaje_Salida": "120V/240V AC / 24V/48V",
        "Altura_Total_m": 2.62,
        "Altura_Pala_m": 2.00,
        "Diametro_Rotor_m": 1.70,
        "Peso_Total_kg": 336.0,
        "Material_Palas": "Aluminio anodizado reciclable",
        "Material_Chasis": "Acero estructural A36 (Caja 1x1 m)",
        "Vida_Diseno_Anos": 20,
        "Cimentacion_Requerida": "Base de concreto 1.0x1.0x2.2m"
    },
    {
        "Modelo": "AL13 Power Tower (6 Mód)",
        "Numero_Parte": "FT AL13-6M",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT Modular (Palas cruzadas a 90°)",
        "Potencia_Nominal_W": 5000,
        "Viento_Potencia_Nominal_ms": 12.0,
        "Produccion_12ms_Aislada_W": 2100.0,
        "Produccion_12ms_Cluster5_Total_W": 21000.0,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico + Freno mecánico",
        "Tipo_Generador": "PMSG de 5 kW",
        "Polos_Generador": 24,
        "Voltaje_Salida": "120V/240V o Trifásico / 48V",
        "Altura_Total_m": 7.50,
        "Altura_Pala_m": 6.00,
        "Diametro_Rotor_m": 1.70,
        "Peso_Total_kg": 588.0,
        "Material_Palas": "Aluminio anodizado reciclable",
        "Material_Chasis": "Acero A36 + Poste estabilizador (70 kg)",
        "Vida_Diseno_Anos": 20,
        "Cimentacion_Requerida": "Zapata 2.5x2.5x0.9m + Anclaje para poste"
    },
    {
        "Modelo": "AL13 Power Tower (8 Mód)",
        "Numero_Parte": "FT AL13-8M",
        "Clase_IEC": "IEC 61400 Class IV",
        "Tipo_Rotor": "VAWT Modular (Palas cruzadas a 90°)",
        "Potencia_Nominal_W": 10000,
        "Viento_Potencia_Nominal_ms": 13.5,
        "Produccion_12ms_Aislada_W": 3500.0,
        "Produccion_12ms_Cluster5_Total_W": 35000.0,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico + Freno mecánico",
        "Tipo_Generador": "PMSG de 10 kW",
        "Polos_Generador": 24,
        "Voltaje_Salida": "240V / Trifásico / 48V",
        "Altura_Total_m": 9.50,
        "Altura_Pala_m": 8.00,
        "Diametro_Rotor_m": 1.70,
        "Peso_Total_kg": 714.0,
        "Material_Palas": "Aluminio anodizado reciclable",
        "Material_Chasis": "Acero A36 + Poste estabilizador reforzado",
        "Vida_Diseno_Anos": 20,
        "Cimentacion_Requerida": "Zapata 2.5x2.5x1.2m + Poste lateral a 1280 mm"
    },
    {
        "Modelo": "Eco-Roof Energy Hub (Flat - 3 Turbines)",
        "Numero_Parte": "FT EcoRoof-Flat-3",
        "Clase_IEC": "N/A",
        "Tipo_Rotor": "3 Turbinas VAWT (1m) en plataforma plana",
        "Potencia_Nominal_W": 300,
        "Viento_Potencia_Nominal_ms": 14.5,
        "Produccion_12ms_Aislada_W": None,
        "Produccion_12ms_Cluster5_Total_W": None,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico automático",
        "Tipo_Generador": "PMSG (Capacidad solar aprox: 2 x 100W)",
        "Polos_Generador": 8,
        "Voltaje_Salida": "Controladores híbridos o separados",
        "Altura_Total_m": None,
        "Altura_Pala_m": 1.149,
        "Diametro_Rotor_m": 0.55,
        "Peso_Total_kg": 196.5,
        "Material_Palas": "Plástico ABS reciclable",
        "Material_Chasis": "Plataforma plana. Cajas contrapeso 300x315x150 mm",
        "Vida_Diseno_Anos": 40,
        "Cimentacion_Requerida": "Instalación sin perforaciones (Efecto Bouquet integrado)"
    },
    {
        "Modelo": "Eco-Roof Energy Hub (Flat - 5 Turbines)",
        "Numero_Parte": "FT EcoRoof-Flat-5",
        "Clase_IEC": "N/A",
        "Tipo_Rotor": "5 Turbinas VAWT (1m) en plataforma plana",
        "Potencia_Nominal_W": 500,
        "Viento_Potencia_Nominal_ms": 14.5,
        "Produccion_12ms_Aislada_W": None,
        "Produccion_12ms_Cluster5_Total_W": None,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico automático",
        "Tipo_Generador": "PMSG (Capacidad solar aprox: 4 x 100W)",
        "Polos_Generador": 8,
        "Voltaje_Salida": "Controladores híbridos o separados",
        "Altura_Total_m": None,
        "Altura_Pala_m": 1.149,
        "Diametro_Rotor_m": 0.55,
        "Peso_Total_kg": 185.3,
        "Material_Palas": "Plástico ABS reciclable",
        "Material_Chasis": "Sistema de balancín para nivelación simétrica",
        "Vida_Diseno_Anos": 40,
        "Cimentacion_Requerida": "Instalación sin perforaciones"
    },
    {
        "Modelo": "Eco-Roof Energy Hub (Slanted)",
        "Numero_Parte": "FT EcoRoof-Slanted",
        "Clase_IEC": "N/A",
        "Tipo_Rotor": "Módulos de 3 Turbinas VAWT (1m) en techo inclinado",
        "Potencia_Nominal_W": 300,
        "Viento_Potencia_Nominal_ms": 14.5,
        "Produccion_12ms_Aislada_W": None,
        "Produccion_12ms_Cluster5_Total_W": None,
        "Velocidad_CutIn_ms": 0.7,
        "Velocidad_Supervivencia_ms": 54.0,
        "Sistema_Frenado": "Electrónico automático",
        "Tipo_Generador": "PMSG (Capacidad solar aprox: 2x400W o 4x400W por módulo)",
        "Polos_Generador": 8,
        "Voltaje_Salida": "Controladores híbridos",
        "Altura_Total_m": None,
        "Altura_Pala_m": 1.149,
        "Diametro_Rotor_m": 0.55,
        "Peso_Total_kg": 207.0,
        "Material_Palas": "Plástico ABS reciclable",
        "Material_Chasis": "Vigas conectadas, puntos de goma de alta fricción",
        "Vida_Diseno_Anos": 40,
        "Cimentacion_Requerida": "Sin perforaciones. Ángulo máximo de techo: 3°"
    }
]

def get_flowerturbines_df():
    """Retorna el DataFrame unificado de especificaciones de Flower Turbines."""
    return pd.DataFrame(FLOWERTURBINES_SPECS)

if __name__ == "__main__":
    df = get_flowerturbines_df()
    print(df)
